### ISSUE TITLE
Removal Request

### ISSUE THREAD

**Issue by AnarchaFemme** [pegasy/glyphs.wf#33]
Warframe Community Discord -
Hey, I'd just like to request you remove our global code (even though it's pretty easy to guess). We're updating our glyph and would prefer it not be publicly known until our new glyph is live - which according to DE should be in about two weeks. I'll contact you at the point it is okay to re-add it.

Thanks!
NervousTrashcat
Feel free to add me on Discord: Trashcat#6969 <@90167208839217152>

**Comment by pegasy** [comment]
Sure, can wait with adding the global code for your glyph, let me know when you want it added!

**Comment by AnarchaFemme** [comment]
Thanks for that!
Our new glyph is now live as of today's PC patch, so feel free to re-add the global code: WARFRAMECOMMUNITYDISCORD
