### ISSUE TITLE
Please update my Glyph: "Etainted"

### ISSUE THREAD

**Issue by EtainTV** [pegasy/glyphs.wf#35]
Hello. Sorry if this isn't the correct to way to do this, but I don't see any other way to apologize. I would like the information under my glyph to be removed as I haven't made/ played warframe in awhile. I am no longer apart of their Partner program so I will not be requesting anymore codes. Thank you.

**Comment by zopney** [comment]
Apparently, I was distracted in October to see this.

No acquisition information is present underneath the page, so no information was needed to be removed. Please reopen the issue if clarification is needed.
