### ISSUE TITLE
Use content.warframe images

### ISSUE THREAD

**Issue by OrangutanGaming** [pegasy/glyphs.wf#5]
http://content.warframe.com/MobileExport/Lotus/Interface/Icons/Player/ContentCreators/...
e.g. http://content.warframe.com/MobileExport/Lotus/Interface/Icons/Player/ContentCreators/13angTV.png

**Comment by pegasy** [comment]
Closed with https://github.com/pegasy/glyphs.wf/commit/2f0b1c803ebe931499704c313fb39a359d9b795c
