### ISSUE TITLE
DesRPG

### ISSUE THREAD

**Issue by nihaals** [pegasy/glyphs.wf#9]
https://glyphs.wf/wf-partner/desrpg

- [x] Image
- [ ] Steps

Possible remove or make it obvious that the glyph no longer exists?

**Comment by OrangutanGaming** [comment]
The glyph is completely removed and in people's inventories it shows a normal lotus glyph (http://content.warframe.com/MobileExport/Lotus/Interface/Icons/Player/ContentCreators/DesRPG.png)
It isn't obtainable in any way, and the file should either be deleted or have some kind of strike through the name and made obvious it doesn't exist. There could even be some kind of archive page of all the deal glyphs.

**Comment by zopney** [comment]
It seems the page has been updated to reflect this request, but would removal of DesRPG's social be considered? It seems pointless to attempt to update social information for a glyph that no longer exists.

Also, as an information freak, I'd love to see more sections of the site dedicated to information, which I questioned in #27 issue.
